apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: curology-takehome
    role: web
  ports:
    - name: http
      port: 8000
      targetPort: gunicorn

